# Numpy

In [ ]:
import numpy as np 
numeros = np.array([12,33,7,7,8,88,90,3,2,6,76,4])#cria uma array de 1 dimensão
print(numeros)
print('.............................................................................................................')
m = np.array([[1,2,3], [1,5,6], [0,8,9]])#cria um array bidimesional
print(m)
print('.............................................................................................................')
print(numeros.shape)#mostra a dimensao da array
print(m.shape)

print('.............................................................................................................')
print(numeros.size)#mostra a quantidade de elementos
print(m.size)


print('.............................................................................................................')
print(m)

[12 33  7  7  8 88 90  3  2  6 76  4]
.............................................................................................................
[[1 2 3]
 [1 5 6]
 [0 8 9]]
.............................................................................................................
(12,)
(3, 3)
.............................................................................................................
12
9
.............................................................................................................
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

